### ISSUE TITLE
Reading Access

### ISSUE THREAD

**Issue by dmadisetti** [D4BL-DMV/dbl-legal-directory#9]
from slack by @emhsieh:

![image](https://user-images.githubusercontent.com/2689338/136436839-68558e15-f518-4932-ab32-3423bcba9b1a.png)

ward 7, 8, 5 estimated % of adults at level 1 (ages 3-6) about 50%

Another article mentions an adult charter school in DC, most students enter the school around a 4th-5th grade reading level (will link source.)

**Comment by emhsieh** [comment]
Using [Hemingway Editor ](https://hemingwayapp.com/) to try to reduce reading levels:

Current: 42 organizations providing free legal services in Washington DC (Grade 12)
Suggestion: 42 organizations give free legal services in DC (Grade 6)

Current: Learn about organizations and programs offering services for those in need of legal assistance who cannot afford it. (Grade 13)
Suggestion: Learn about places offering services for those in need of legal help who cannot afford it. (Grade 8)

Current: Under Want to learn more? (Grade 16.)  I don't know if we are "allowed" to edit this part. Is it from D4BL national? 
Suggestion: (Grade 12) Data for Black Lives is a movement of activists, organizers, and mathematicians. Our mission is to use data science to create concrete and measurable change in the lives of Black people. 
Big data and algorithms have penetrated every aspect of our lives. These new data systems have tremendous potential to empower communities of color. Statistical modeling, data visualization, and crowd-sourcing are powerful tools. They can fight bias, build progressive movements, and promote civic engagement. 
But history tells a different story, one where data is often wielded as an instrument of oppression.  Where it reinforces inequality and perpetuates injustice. Redlining was a data-driven operation that excluded Black communities from  financial services. More recently, predictive policing, risk-based sentencing, and predatory lending, are troubling variations. Today, discrimination is a high-tech enterprise.

**Comment by dmadisetti** [comment]
We made these changes right?
